# Generated by Django 3.2.8 on 2021-10-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attending',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watching',
        ),
    ]
