# Generated by Django 3.2.8 on 2021-10-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211025_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
    ]
