# Generated by Django 3.2.8 on 2021-10-26 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('tm_url', models.TextField()),
                ('img_url', models.TextField()),
                ('start', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='attending', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postalCode', models.IntegerField()),
                ('venueId', models.CharField(max_length=100)),
                ('venue_url', models.TextField()),
                ('img_url', models.TextField()),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_reviews', to='wander.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('event', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='wander.event')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_location', to='wander.venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='viewers',
            field=models.ManyToManyField(related_name='viewing', to=settings.AUTH_USER_MODEL),
        ),
    ]
