# Generated by Django 3.2.8 on 2021-10-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('eventbrite_url', models.TextField()),
                ('img_url', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('seen', models.BooleanField(default=False)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='wander.user')),
            ],
        ),
    ]
