# Generated by Django 3.2.8 on 2021-10-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0003_event_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
    ]
