# Generated by Django 3.2.8 on 2021-10-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0004_remove_event_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='user_list', to='wander.Event'),
        ),
    ]
