# Generated by Django 3.2.8 on 2021-10-24 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wander', '0006_auto_20211023_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='viewers',
            field=models.ManyToManyField(related_name='viewing', to=settings.AUTH_USER_MODEL),
        ),
    ]
