# Generated by Django 3.2.8 on 2021-10-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0008_auto_20211024_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='venue_review', to='wander.review'),
        ),
    ]
