# Generated by Django 3.2.8 on 2021-10-24 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0009_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='venue_review', to='wander.venue'),
        ),
    ]
