# Generated by Django 3.2.8 on 2021-10-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0013_alter_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='venue',
        ),
        migrations.AddField(
            model_name='venue',
            name='reviews',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='wander.review'),
        ),
    ]
