# Generated by Django 3.2.8 on 2021-10-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0014_auto_20211025_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reviews',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='wander.review'),
        ),
    ]
