# Generated by Django 3.2.8 on 2021-10-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0015_alter_venue_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='wander.venue'),
        ),
    ]
